---
#
# Configuration file for 'dhcp_infoblox' dhcp provider
#
# use :server setting in dhcp.yml if you are managing a dhcp server which is not localhost
# Infoblox settings:
:infoblox_user: "infoblox"
:infoblox_pw: "infoblox"
