---
#
# Configuration file for 'dhcp_infoblox' dhcp provider
#
# use :server setting in dhcp.yml if you are managing a dhcp server which is not localhost
# Infoblox settings:
:infoblox_user: "infoblox"
:infoblox_pw: "infoblox"
#Record type to manage. Can be "host" or "fixed_address"
:record_type: 'host'
#infoblox api version
:wapi_version: '2.0'
#Use  pre-definded ranges in networks to find available IP's
:range: false
#Load subnets from Infoblox, if false subnets from dhcp.yml are loaded
#:infoblox_subnets: true
#:restart_sleep: 15
#:restart: true
